// ── ai-tables.js ───────────────────────────────────────────────────────────
// GENERATED by arena-solver/tools/gen-ai-tables.mjs — do not hand-edit.
// The AI scripts' literal lookup tables, at pokeemerald a3c551fe.
//
// Extracted rather than transcribed: both are long enough that a hand copy is
// a silent-error risk, and both are read with a -1 sentinel, so the generator
// takes the terminator as the extent instead of a hard-coded length.

// AI_CV_Encore's if_not_in_bytes table (data/battle_ai_scripts.s:1703-1766).
// 62 effects. The AI encores the target's last move only when that
// move's EFFECT is in here — i.e. when locking the target into it helps.
export const ENCORE_ENCOURAGED_EFFECTS = new Set(["EFFECT_DREAM_EATER","EFFECT_ATTACK_UP","EFFECT_DEFENSE_UP","EFFECT_SPEED_UP","EFFECT_SPECIAL_ATTACK_UP","EFFECT_HAZE","EFFECT_ROAR","EFFECT_CONVERSION","EFFECT_TOXIC","EFFECT_LIGHT_SCREEN","EFFECT_REST","EFFECT_SUPER_FANG","EFFECT_SPECIAL_DEFENSE_UP_2","EFFECT_CONFUSE","EFFECT_POISON","EFFECT_PARALYZE","EFFECT_LEECH_SEED","EFFECT_SPLASH","EFFECT_ATTACK_UP_2","EFFECT_ENCORE","EFFECT_CONVERSION_2","EFFECT_LOCK_ON","EFFECT_HEAL_BELL","EFFECT_MEAN_LOOK","EFFECT_NIGHTMARE","EFFECT_PROTECT","EFFECT_SKILL_SWAP","EFFECT_FORESIGHT","EFFECT_PERISH_SONG","EFFECT_SANDSTORM","EFFECT_ENDURE","EFFECT_SWAGGER","EFFECT_ATTRACT","EFFECT_SAFEGUARD","EFFECT_RAIN_DANCE","EFFECT_SUNNY_DAY","EFFECT_BELLY_DRUM","EFFECT_PSYCH_UP","EFFECT_FUTURE_SIGHT","EFFECT_FAKE_OUT","EFFECT_STOCKPILE","EFFECT_SPIT_UP","EFFECT_SWALLOW","EFFECT_HAIL","EFFECT_TORMENT","EFFECT_WILL_O_WISP","EFFECT_FOLLOW_ME","EFFECT_CHARGE","EFFECT_TRICK","EFFECT_ROLE_PLAY","EFFECT_INGRAIN","EFFECT_RECYCLE","EFFECT_KNOCK_OFF","EFFECT_SKILL_SWAP","EFFECT_IMPRISON","EFFECT_REFRESH","EFFECT_GRUDGE","EFFECT_TEETER_DANCE","EFFECT_MUD_SPORT","EFFECT_WATER_SPORT","EFFECT_DRAGON_DANCE","EFFECT_CAMOUFLAGE"]);

// AI_CV_MirrorMove's if_in_hwords table (data/battle_ai_scripts.s:854-894).
// 39 moves, mapped onto this engine's own move names.
export const MIRROR_MOVE_ENCOURAGED = new Set(["Sleep Powder","Lovely Kiss","Spore","Hypnosis","Sing","GrassWhistle","Shadow Punch","Sand-Attack","SmokeScreen","Toxic","Guillotine","Horn Drill","Fissure","Sheer Cold","Cross Chop","Aeroblast","Confuse Ray","Sweet Kiss","Screech","Cotton Spore","Scary Face","Fake Tears","Metal Sound","Thunder Wave","Glare","Poison Powder","Shadow Ball","DynamicPunch","Hyper Beam","ExtremeSpeed","Thief","Covet","Attract","Swagger","Torment","Flatter","Trick","Superpower","Skill Swap"]);
