// ── item-data.js ──────────────────────────────────────────
// GENERATED by arena-solver/tools/gen-item-table.mjs — do not hand-edit.
// Every held item the Lv50 pool uses, with its holdEffect and holdEffectParam
// from src/data/items.h at pokeemerald a3c551fe.
//
// `sets` / `cells` are the pool's own usage counts, carried so any claim about
// an item's blast radius can be read off the table instead of re-derived.
export const ITEM_DATA = {
  "Quick Claw": { holdEffect: "HOLD_EFFECT_QUICK_CLAW", param: 20, constant: "ITEM_QUICK_CLAW", srcLine: 2235, sets: 80, cells: 141 },
  "Lum Berry": { holdEffect: "HOLD_EFFECT_CURE_STATUS", param: 0, constant: "ITEM_LUM_BERRY", srcLine: 1733, sets: 80, cells: 139 },
  "Leftovers": { holdEffect: "HOLD_EFFECT_LEFTOVERS", param: 10, constant: "ITEM_LEFTOVERS", srcLine: 2445, sets: 75, cells: 134 },
  "BrightPowder": { holdEffect: "HOLD_EFFECT_EVASION_UP", param: 10, constant: "ITEM_BRIGHT_POWDER", srcLine: 2186, sets: 82, cells: 130 },
  "Focus Band": { holdEffect: "HOLD_EFFECT_FOCUS_BAND", param: 10, constant: "ITEM_FOCUS_BAND", srcLine: 2395, sets: 80, cells: 129 },
  "Scope Lens": { holdEffect: "HOLD_EFFECT_SCOPE_LENS", param: 0, constant: "ITEM_SCOPE_LENS", srcLine: 2420, sets: 57, cells: 89 },
  "Chesto Berry": { holdEffect: "HOLD_EFFECT_CURE_SLP", param: 0, constant: "ITEM_CHESTO_BERRY", srcLine: 1633, sets: 49, cells: 80 },
  "Shell Bell": { holdEffect: "HOLD_EFFECT_SHELL_BELL", param: 8, constant: "ITEM_SHELL_BELL", srcLine: 2690, sets: 43, cells: 75 },
  "Sitrus Berry": { holdEffect: "HOLD_EFFECT_RESTORE_HP", param: 30, constant: "ITEM_SITRUS_BERRY", srcLine: 1747, sets: 51, cells: 58 },
  "King's Rock": { holdEffect: "HOLD_EFFECT_FLINCH", param: 10, constant: "ITEM_KINGS_ROCK", srcLine: 2284, sets: 28, cells: 47 },
  "Salac Berry": { holdEffect: "HOLD_EFFECT_SPEED_UP", param: 4, constant: "ITEM_SALAC_BERRY", srcLine: 2073, sets: 22, cells: 40 },
  "White Herb": { holdEffect: "HOLD_EFFECT_RESTORE_STATS", param: 0, constant: "ITEM_WHITE_HERB", srcLine: 2199, sets: 25, cells: 39 },
  "Persim Berry": { holdEffect: "HOLD_EFFECT_CURE_CONFUSION", param: 0, constant: "ITEM_PERSIM_BERRY", srcLine: 1719, sets: 31, cells: 37 },
  "Cheri Berry": { holdEffect: "HOLD_EFFECT_CURE_PAR", param: 0, constant: "ITEM_CHERI_BERRY", srcLine: 1619, sets: 21, cells: 29 },
  "Petaya Berry": { holdEffect: "HOLD_EFFECT_SP_ATTACK_UP", param: 4, constant: "ITEM_PETAYA_BERRY", srcLine: 2086, sets: 16, cells: 24 },
  "Choice Band": { holdEffect: "HOLD_EFFECT_CHOICE_BAND", param: 0, constant: "ITEM_CHOICE_BAND", srcLine: 2272, sets: 13, cells: 23 },
  "Liechi Berry": { holdEffect: "HOLD_EFFECT_ATTACK_UP", param: 4, constant: "ITEM_LIECHI_BERRY", srcLine: 2047, sets: 13, cells: 18 },
  "TwistedSpoon": { holdEffect: "HOLD_EFFECT_PSYCHIC_POWER", param: 10, constant: "ITEM_TWISTED_SPOON", srcLine: 2626, sets: 10, cells: 12 },
  "Rawst Berry": { holdEffect: "HOLD_EFFECT_CURE_BRN", param: 0, constant: "ITEM_RAWST_BERRY", srcLine: 1661, sets: 8, cells: 10 },
  "Mystic Water": { holdEffect: "HOLD_EFFECT_WATER_POWER", param: 10, constant: "ITEM_MYSTIC_WATER", srcLine: 2561, sets: 7, cells: 8 },
  "Sharp Beak": { holdEffect: "HOLD_EFFECT_FLYING_POWER", param: 10, constant: "ITEM_SHARP_BEAK", srcLine: 2574, sets: 4, cells: 8 },
  "Thick Club": { holdEffect: "HOLD_EFFECT_THICK_CLUB", param: 0, constant: "ITEM_THICK_CLUB", srcLine: 2753, sets: 4, cells: 8 },
  "Soft Sand": { holdEffect: "HOLD_EFFECT_GROUND_POWER", param: 10, constant: "ITEM_SOFT_SAND", srcLine: 2483, sets: 5, cells: 6 },
  "NeverMeltIce": { holdEffect: "HOLD_EFFECT_ICE_POWER", param: 10, constant: "ITEM_NEVER_MELT_ICE", srcLine: 2600, sets: 4, cells: 5 },
  "Magnet": { holdEffect: "HOLD_EFFECT_ELECTRIC_POWER", param: 10, constant: "ITEM_MAGNET", srcLine: 2548, sets: 3, cells: 5 },
  "Poison Barb": { holdEffect: "HOLD_EFFECT_POISON_POWER", param: 10, constant: "ITEM_POISON_BARB", srcLine: 2587, sets: 3, cells: 4 },
  "Miracle Seed": { holdEffect: "HOLD_EFFECT_GRASS_POWER", param: 10, constant: "ITEM_MIRACLE_SEED", srcLine: 2509, sets: 2, cells: 3 },
  "Charcoal": { holdEffect: "HOLD_EFFECT_FIRE_POWER", param: 10, constant: "ITEM_CHARCOAL", srcLine: 2639, sets: 2, cells: 3 },
  "Leppa Berry": { holdEffect: "HOLD_EFFECT_RESTORE_PP", param: 10, constant: "ITEM_LEPPA_BERRY", srcLine: 1689, sets: 2, cells: 3 },
};
